# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ hack-cicd ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.99.0
        with:
          ruby-version: 'default'

      - name: Sign & Build IPA using Fastlane
        uses: maierj/fastlane-action@v2.2.0
        with:
          lane: 'for_internal_distro'
          subdirectory: 'iOS_SDK'
          skip-tracking: true
          verbose: true

    distribute:
      runs-on: ubuntu-latest
      steps:
        - name: Setup NPM
          uses: actions/setup-node@v2
          with:
            node-version: '14'

        - name: Install App Center CLI
          run: npm install -g appcenter-cli

        - name: Upload IPA
          run: echo todo